// Mock Data for Development
const mockTools = [
  {
    id: 1,
    name: "文心一格",
    description: "百度推出的AI绘画工具，一语成画，支持国风、油画、水彩等多种艺术风格。",
    icon: "",
    cover: "",
    url: "https://yige.baidu.com",
    category: "painting",
    tags: ["AI绘画", "国产", "百度"],
    features: ["一语成画", "多种风格", "零门槛创作", "高清输出"],
    pricing: "freemium",
    rating: 4.7,
    view_count: 18500,
    favorite_count: 4200,
    status: "active",
    is_featured: true,
    is_hot: true,
    created_at: "2024-01-01T00:00:00",
    updated_at: "2024-01-15T00:00:00"
  },
  {
    id: 2,
    name: "通义万相",
    description: "阿里云推出的AI视觉生成平台，支持图像生成、视频生成、3D内容创作。",
    icon: "",
    cover: "",
    url: "https://tongyi.aliyun.com/wanxiang",
    category: "multimedia",
    tags: ["AI视频", "图像生成", "阿里云"],
    features: ["文生图", "文生视频", "图像编辑", "3D生成"],
    pricing: "freemium",
    rating: 4.8,
    view_count: 22000,
    favorite_count: 5100,
    status: "active",
    is_featured: true,
    is_hot: true,
    created_at: "2024-01-02T00:00:00",
    updated_at: "2024-01-16T00:00:00"
  },
  {
    id: 3,
    name: "豆包",
    description: "字节跳动推出的AI助手，日活极高，支持智能对话、内容创作、生活助手等功能。",
    icon: "",
    cover: "",
    url: "https://www.doubao.com",
    category: "efficiency",
    tags: ["AI对话", "国产", "字节跳动"],
    features: ["智能对话", "内容创作", "生活助手", "多场景应用"],
    pricing: "free",
    rating: 4.6,
    view_count: 35000,
    favorite_count: 8900,
    status: "active",
    is_featured: true,
    is_hot: true,
    created_at: "2024-01-03T00:00:00",
    updated_at: "2024-01-17T00:00:00"
  },
  {
    id: 4,
    name: "通义千问",
    description: "阿里云大模型，深度整合阿里生态，支持淘宝、飞猪、高德等服务闭环。",
    icon: "",
    cover: "",
    url: "https://tongyi.aliyun.com",
    category: "efficiency",
    tags: ["AI对话", "阿里云", "生态整合"],
    features: ["智能对话", "生态闭环", "办事能力", "多模态"],
    pricing: "freemium",
    rating: 4.7,
    view_count: 28000,
    favorite_count: 6500,
    status: "active",
    is_featured: true,
    is_hot: true,
    created_at: "2024-01-04T00:00:00",
    updated_at: "2024-01-18T00:00:00"
  },
  {
    id: 5,
    name: "智谱清言",
    description: "智谱AI推出的对话助手，基于ChatGLM模型，擅长学术写作和复杂逻辑推理。",
    icon: "",
    cover: "",
    url: "https://chatglm.cn",
    category: "efficiency",
    tags: ["AI对话", "学术写作", "国产"],
    features: ["逻辑推理", "学术写作", "多轮对话", "指令遵循"],
    pricing: "freemium",
    rating: 4.6,
    view_count: 16000,
    favorite_count: 3800,
    status: "active",
    is_featured: true,
    is_hot: false,
    created_at: "2024-01-05T00:00:00",
    updated_at: "2024-01-19T00:00:00"
  },
  {
    id: 6,
    name: "即梦AI",
    description: "国产AI视频生成工具，支持多模态输入，文生视频效果出色。",
    icon: "",
    cover: "",
    url: "https://jimeng.jianying.com",
    category: "multimedia",
    tags: ["AI视频", "国产", "多模态"],
    features: ["文生视频", "多模态输入", "高质量生成", "快速渲染"],
    pricing: "freemium",
    rating: 4.5,
    view_count: 12000,
    favorite_count: 2900,
    status: "active",
    is_featured: false,
    is_hot: true,
    created_at: "2024-01-06T00:00:00",
    updated_at: "2024-01-20T00:00:00"
  },
  {
    id: 7,
    name: "可灵AI",
    description: "快手推出的AI视频生成工具，支持数字人生成、运镜控制，视频生成能力领先。",
    icon: "",
    cover: "",
    url: "https://klingai.kuaishou.com",
    category: "multimedia",
    tags: ["AI视频", "数字人", "快手"],
    features: ["文生视频", "数字人", "运镜控制", "长视频"],
    pricing: "freemium",
    rating: 4.7,
    view_count: 19000,
    favorite_count: 4500,
    status: "active",
    is_featured: true,
    is_hot: true,
    created_at: "2024-01-07T00:00:00",
    updated_at: "2024-01-21T00:00:00"
  },
  {
    id: 8,
    name: "DeepSeek",
    description: "国产AI大模型，擅长复杂逻辑推理、深度阅读和代码任务，专业人士首选。",
    icon: "",
    cover: "",
    url: "https://www.deepseek.com",
    category: "efficiency",
    tags: ["AI对话", "代码", "逻辑推理"],
    features: ["逻辑推理", "代码生成", "深度阅读", "报告撰写"],
    pricing: "freemium",
    rating: 4.8,
    view_count: 21000,
    favorite_count: 5600,
    status: "active",
    is_featured: true,
    is_hot: true,
    created_at: "2024-01-08T00:00:00",
    updated_at: "2024-01-22T00:00:00"
  },
  {
    id: 9,
    name: "腾讯元宝",
    description: "腾讯推出的AI助手，深度绑定微信生态，适合办公纪要、日程管理等场景。",
    icon: "",
    cover: "",
    url: "https://yuanbao.tencent.com",
    category: "efficiency",
    tags: ["AI对话", "微信生态", "腾讯"],
    features: ["办公助手", "微信集成", "日程管理", "会议纪要"],
    pricing: "free",
    rating: 4.5,
    view_count: 14000,
    favorite_count: 3200,
    status: "active",
    is_featured: false,
    is_hot: false,
    created_at: "2024-01-09T00:00:00",
    updated_at: "2024-01-23T00:00:00"
  },
  {
    id: 10,
    name: "Midjourney",
    description: "AI绘画领域的领导者，通过文字描述生成高质量艺术图像。",
    icon: "",
    cover: "",
    url: "https://midjourney.com",
    category: "painting",
    tags: ["AI绘画", "图像生成", "艺术创作"],
    features: ["文字生成图像", "多种艺术风格", "高清输出", "风格迁移"],
    pricing: "paid",
    rating: 4.8,
    view_count: 12580,
    favorite_count: 3250,
    status: "active",
    is_featured: false,
    is_hot: true,
    created_at: "2024-01-10T00:00:00",
    updated_at: "2024-01-24T00:00:00"
  },
  {
    id: 11,
    name: "ChatGPT",
    description: "OpenAI开发的AI对话助手，支持自然语言对话、代码生成、文本分析。",
    icon: "",
    cover: "",
    url: "https://chat.openai.com",
    category: "efficiency",
    tags: ["AI对话", "文本生成", "代码助手"],
    features: ["智能对话", "代码生成", "文本分析", "多语言支持"],
    pricing: "freemium",
    rating: 4.9,
    view_count: 25680,
    favorite_count: 8950,
    status: "active",
    is_featured: false,
    is_hot: true,
    created_at: "2024-01-11T00:00:00",
    updated_at: "2024-01-25T00:00:00"
  },
  {
    id: 12,
    name: "Runway",
    description: "AI视频生成和编辑平台，支持文字生成视频、视频编辑、特效添加。",
    icon: "",
    cover: "",
    url: "https://runway.ml",
    category: "multimedia",
    tags: ["AI视频", "视频编辑", "特效"],
    features: ["文字生成视频", "视频编辑", "AI特效", "绿幕抠像"],
    pricing: "freemium",
    rating: 4.5,
    view_count: 7890,
    favorite_count: 1560,
    status: "active",
    is_featured: false,
    is_hot: false,
    created_at: "2024-01-12T00:00:00",
    updated_at: "2024-01-26T00:00:00"
  }
]

const mockArticles = [
  {
    id: 1,
    title: "2024年最值得关注的10个AI绘画工具",
    summary: "AI绘画技术飞速发展，本文盘点2024年最值得关注的10个AI绘画工具，帮助你选择最适合的创作工具。",
    content: "详细内容...",
    cover: "https://via.placeholder.com/400x200/6366f1/ffffff?text=AI+Painting",
    author: "AIHub编辑部",
    source: "AIHub3000",
    view_count: 3580,
    is_published: true,
    published_at: "2024-01-20T10:00:00",
    created_at: "2024-01-20T08:00:00",
    updated_at: "2024-01-20T10:00:00"
  },
  {
    id: 2,
    title: "ChatGPT vs Claude：哪个AI助手更适合你？",
    summary: "详细对比ChatGPT和Claude的功能特点、使用场景和定价策略，帮助你做出选择。",
    content: "详细内容...",
    cover: "https://via.placeholder.com/400x200/10b981/ffffff?text=GPT+vs+Claude",
    author: "AIHub编辑部",
    source: "AIHub3000",
    view_count: 2890,
    is_published: true,
    published_at: "2024-01-19T14:00:00",
    created_at: "2024-01-19T12:00:00",
    updated_at: "2024-01-19T14:00:00"
  },
  {
    id: 3,
    title: "如何用AI工具提升工作效率？",
    summary: "分享5个实用技巧，教你如何利用AI工具大幅提升日常工作效率。",
    content: "详细内容...",
    cover: "https://via.placeholder.com/400x200/f59e0b/ffffff?text=AI+Efficiency",
    author: "AIHub编辑部",
    source: "AIHub3000",
    view_count: 4120,
    is_published: true,
    published_at: "2024-01-18T09:00:00",
    created_at: "2024-01-18T07:00:00",
    updated_at: "2024-01-18T09:00:00"
  }
]

const mockCategories = {
  categories: [
    { key: "painting", name: "AI绘画", icon: "palette", description: "图像生成、编辑、设计", color: "#ec4899" },
    { key: "efficiency", name: "AI效率", icon: "rocket", description: "写作、翻译、编程", color: "#6366f1" },
    { key: "multimedia", name: "AI多媒体", icon: "video", description: "视频、音频、3D", color: "#f59e0b" }
  ]
}

module.exports = {
  mockTools,
  mockArticles,
  mockCategories
}